version: "3.8"

services:
  ${artifactId}:
    container_name: ${artifactId}
    build:
      context: ../
      dockerfile: docker/${artifactId}.Dockerfile
    environment:
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
    ports:
      - ${serverPort}:${serverPort}
